/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealtyIndexRouteImport } from './routes/realty/index'
import { Route as DgiPickIndexRouteImport } from './routes/dgi-pick/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtyIndexRoute = RealtyIndexRouteImport.update({
  id: '/realty/',
  path: '/realty/',
  getParentRoute: () => rootRouteImport,
} as any)
const DgiPickIndexRoute = DgiPickIndexRouteImport.update({
  id: '/dgi-pick/',
  path: '/dgi-pick/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dgi-pick/': typeof DgiPickIndexRoute
  '/realty/': typeof RealtyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dgi-pick': typeof DgiPickIndexRoute
  '/realty': typeof RealtyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dgi-pick/': typeof DgiPickIndexRoute
  '/realty/': typeof RealtyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dgi-pick/' | '/realty/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dgi-pick' | '/realty'
  id: '__root__' | '/' | '/dgi-pick/' | '/realty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DgiPickIndexRoute: typeof DgiPickIndexRoute
  RealtyIndexRoute: typeof RealtyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realty/': {
      id: '/realty/'
      path: '/realty'
      fullPath: '/realty/'
      preLoaderRoute: typeof RealtyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dgi-pick/': {
      id: '/dgi-pick/'
      path: '/dgi-pick'
      fullPath: '/dgi-pick/'
      preLoaderRoute: typeof DgiPickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DgiPickIndexRoute: DgiPickIndexRoute,
  RealtyIndexRoute: RealtyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
